db:
  jdbc:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/stationsdb
    user: sa
    password: 
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    hbm2ddl:
      auto: create-drop
    show_sql: true